<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class feecategory extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id'             =>  '1',
                'fee_category'   => 'General',
                'br_id'          =>  '1',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '2',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '1',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '3',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '1',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '4',
                'fee_category'   => 'General',
                'br_id'          =>  '2',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '5',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '2',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '6',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '2',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '7',
                'fee_category'   => 'General',
                'br_id'          =>  '3',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '8',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '3',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '9',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '3',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '10',
                'fee_category'   => 'General',
                'br_id'          =>  '4',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '11',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '4',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '12',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '4',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '13',
                'fee_category'   => 'General',
                'br_id'          =>  '5',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '14',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '5',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '15',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '5',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '16',
                'fee_category'   => 'General',
                'br_id'          =>  '6',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '17',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '6',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '18',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '6',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '19',
                'fee_category'   => 'General',
                'br_id'          =>  '7',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '20',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '7',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '21',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '7',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '22',
                'fee_category'   => 'General',
                'br_id'          =>  '8',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '23',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '8',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '24',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '8',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '25',
                'fee_category'   => 'General',
                'br_id'          =>  '9',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '26',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '9',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '27',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '9',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '28',
                'fee_category'   => 'General',
                'br_id'          =>  '10',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '29',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '10',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '30',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '10',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '31',
                'fee_category'   => 'General',
                'br_id'          =>  '11',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '32',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '11',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '33',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '11',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '34',
                'fee_category'   => 'General',
                'br_id'          =>  '12',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '35',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '12',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '36',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '12',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '37',
                'fee_category'   => 'General',
                'br_id'          =>  '13',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '38',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '13',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '39',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '13',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '40',
                'fee_category'   => 'General',
                'br_id'          =>  '14',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '41',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '14',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '42',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '14',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '43',
                'fee_category'   => 'General',
                'br_id'          =>  '15',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '44',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '15',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '45',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '15',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '46',
                'fee_category'   => 'General',
                'br_id'          =>  '16',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '47',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '16',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '48',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '16',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '49',
                'fee_category'   => 'General',
                'br_id'          =>  '17',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '50',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '17',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '51',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '17',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '52',
                'fee_category'   => 'General',
                'br_id'          =>  '18',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '53',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '18',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '54',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '18',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '55',
                'fee_category'   => 'General',
                'br_id'          =>  '19',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '56',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '19',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '57',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '19',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '58',
                'fee_category'   => 'General',
                'br_id'          =>  '20',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '59',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '20',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '60',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '20',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '61',
                'fee_category'   => 'General',
                'br_id'          =>  '21',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '62',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '21',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '63',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '21',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '64',
                'fee_category'   => 'General',
                'br_id'          =>  '22',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '65',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '22',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '66',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '22',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '67',
                'fee_category'   => 'General',
                'br_id'          =>  '23',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '68',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '23',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '69',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '23',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '70',
                'fee_category'   => 'General',
                'br_id'          =>  '24',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '71',
                'fee_category'   => 'NON SAARC NRI',
                'br_id'          =>  '24',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            [
                'id'             =>  '72',
                'fee_category'   => 'SAARC NRI',
                'br_id'          =>  '24',
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
                ],
            ];
        DB::table('feecategory')->insert($data);

    }
}
