<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class feecollectiontype extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data  = [
            [
                'id'               =>  '1',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '2',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '3',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '4',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '5',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '6',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '7',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '2',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '8',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '2',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '9',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '2',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '10',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '2',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '11',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '2',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '12',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '2',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '13',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '3',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '14',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '3',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '15',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '3',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '16',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '3',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '17',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '3',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '18',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '3',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '19',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '4',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '20',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '4',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '21',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '4',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '22',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '4',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '23',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '4',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '24',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '4',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '25',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '5',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '26',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '5',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '27',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '5',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '28',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '5',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '29',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '5',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '30',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '5',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '31',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '6',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '32',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '6',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '33',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '6',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '34',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '6',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '35',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '6',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '36',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '6',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '37',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '7',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '38',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '7',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '39',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '7',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '40',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '7',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '41',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '7',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '42',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '7',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '43',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '8',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '44',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '8',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '45',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '8',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '46',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '8',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '47',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '8',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '48',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '8',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '49',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '9',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '50',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '9',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '51',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '9',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '52',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '9',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '53',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '9',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '54',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '9',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '55',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '10',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '56',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '10',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '57',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '10',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '58',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '10',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '59',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '10',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '60',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '10',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '61',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '11',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '62',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '11',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '63',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '11',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '64',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '11',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '65',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '11',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '66',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '11',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '67',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '12',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '68',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '12',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '69',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '12',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '70',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '12',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '71',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '12',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '72',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '12',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '73',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '13',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '74',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '13',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '75',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '13',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '76',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '13',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '77',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '13',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '78',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '13',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '79',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '14',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '80',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '14',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '81',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '14',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '82',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '14',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '83',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '14',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '84',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '14',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '85',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '15',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '86',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '15',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '87',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '15',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '88',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '15',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '89',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '15',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '90',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '15',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '91',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '16',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '92',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '16',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '93',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '16',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '94',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '16',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '95',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '16',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '96',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '16',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '97',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '17',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '98',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '17',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '99',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '17',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '100',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '17',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '101',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '17',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '102',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '17',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '1',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '2',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '3',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '4',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '5',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '6',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '1',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '2',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '3',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '4',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '5',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '6',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '1',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '2',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '3',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '4',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '5',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '6',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '1',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '2',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '3',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '4',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '5',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '6',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '1',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '2',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '3',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '4',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '5',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '6',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '1',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '2',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '3',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '4',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '5',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '6',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '1',
                'collectionhead'   => 'Academic',
                'collectiondesc'   => 'Academic',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '2',
                'collectionhead'   => 'Academic Misc',
                'collectiondesc'   => 'Academic Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '3',
                'collectionhead'   => 'Hostel',
                'collectiondesc'   => 'Hostel',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '4',
                'collectionhead'   => 'Hostel Misc',
                'collectiondesc'   => 'Hostel Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '5',
                'collectionhead'   => 'Transport',
                'collectiondesc'   => 'Transport',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            [
                'id'               =>  '6',
                'collectionhead'   => 'Transport Misc',
                'collectiondesc'   => 'Transport Misc',
                'br_id'            =>  '1',
                'created_at'       => date('Y-m-d H:i:s'),
                'updated_at'       => date('Y-m-d H:i:s'),
                ],
            
            ];

        DB::table('feecollectiontypes')->insert($data);

    }
}
